<a href="https://colab.research.google.com/github/Shrutikapedamkar/CE889_Neural-Networks/blob/main/NN_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
def sigmoid(z):
  sig= 1/(1+np.exp(-z))
  return sig

In [32]:
input = np.array([[1,6,8,0],[33,2,3,5],[1,6,6,7],[2,9,8,4],[5,6,9,6],[32,13,0,2]])
output= np.array([[1,0,1,0],[0,1,0,1]])
np.shape(input)

(6, 4)

In [33]:
W = np.full((6,2),0.01).T
np.shape(W)

(2, 6)

In [34]:
b = np.full((2,1),0.01)
b

array([[0.01],
       [0.01]])

In [36]:
y= np.dot(W, input)+b
y

array([[0.75, 0.43, 0.35, 0.25],
       [0.75, 0.43, 0.35, 0.25]])

In [37]:
y_output = sigmoid(y)
y_output

array([[0.6791787 , 0.60587367, 0.58661758, 0.5621765 ],
       [0.6791787 , 0.60587367, 0.58661758, 0.5621765 ]])

In [38]:
loss_mse = (1/6)*np.power(np.sum(output - y_output),2)
loss_mse

0.12548182662034824